"set guioptions=acegmt
set guioptions-=r
set guioptions-=L
set guioptions-=T
set guioptions+=ac
set guifont=Monospace\ 11
"set guifont=Monaco:h14
"set guifont=Letter\ Gothic\ Std\ Medium:h14
"set guifont=Letter\ Gothic\ Std\ Bold:h14
set guicursor+=a:blinkon0
set background=light
"let g:solarized_contrast="high"
"let g:solarized_visibility="high"
let g:solarized_diffmode="high"
set lines=60
set columns=100
set lines=60
set columns=100
