"set guioptions=acegmt
set guioptions-=r
set guioptions-=L
set guioptions-=T
set guioptions-=m
set guioptions+=ac
set guifont=Cousine\ for\ Powerline\ 11
set linespace=1
"set guifont=Monaco:h14
"set guifont=Letter\ Gothic\ Std\ Medium:h14
"set guifont=Letter\ Gothic\ Std\ Bold:h14
set guicursor+=a:blinkon0
set background=dark
"let g:solarized_contrast="high"
"let g:solarized_visibility="high"
"let g:solarized_diffmode="high"
set lines=60
set columns=104
