#!/bin/sh

# Give focus back to Firefox after enter flash

window=$(xdotool getwindowfocus)
# window=$(xdotool search --onlyvisible --class iceweasel)
eval "$(xdotool getwindowgeometry --shell "$window")"

xdotool mousemove --window "$window" $((WIDTH - 10)) $((HEIGHT - 10)) click 1
