#!/bin/sh

# Toggle flash player fullscreen, and give focus back to Firefox after exit

get_window_name() {
  xdotool getwindowfocus getwindowname
}

escape_from_flash() {
  window=$(xdotool getwindowfocus)
  # window=$(xdotool search --onlyvisible --class iceweasel)
  eval "$(xdotool getwindowgeometry --shell "$window")"
  xdotool mousemove --window "$window" $((WIDTH - 10)) $((HEIGHT - 10)) click 1
}

if [ x"$1" = x"-e" ]; then
  escape_from_flash
  exit 0
fi

window_name="$(get_window_name)"

case "$window_name" in
  plugin-container)
    # flash player fullscreen
    xdotool key --clearmodifiers Escape
    while [ x"$(get_window_name)" = x"plugin-container" ]
    do
      sleep 0.1
    done
    escape_from_flash
    ;;
  *bilibili*)
    escape_from_flash
    xdotool key --clearmodifiers Escape Home j j mousemove 1443 1008 click --repeat 2 1
    ;;
  *Pentadactyl)
    escape_from_flash
    xdotool key --clearmodifiers Escape Home mousemove --polar 0 0 click --repeat 2 1
    ;;
esac
