#!/bin/sh
# Copyright (c) 2014 Zhong Jianxin <azuwis@gmail.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Thank Stefan Breunig for the original implementation, see
# contrib/measure-net-speed.bash.

# i3status.conf should contain:
# general {
#   output_format = i3bar
# }

# i3 config looks like this:
# bar {
#   status_command exec /usr/share/doc/i3status/contrib/net-speed
# }

interfaces="eth0"

eth0="/sys/class/net/eth0/statistics"

last_rx=0
last_tx=0
rate=""

update_rate() {
    local rx
    local tx
    read rx < "${eth0}/rx_bytes"
    read tx < "${eth0}/tx_bytes"
    rate="$(( ((rx - last_rx) >> 10) / 5 ))K↓ $(( ((tx - last_tx) >> 10) / 5 ))K↑"
    last_rx=$rx
    last_tx=$tx
}

i3status | (read line && echo $line && read line && echo $line && read line && echo $line && update_rate && while :
do
    read line
    update_rate
    echo ",[{\"full_text\":\"${rate}\" },${line#,\[}" || exit 1
done)
