#!/bin/sh

volume() {
    local action="$1"

    local item="PCM"
    amixer sget Master > /dev/null 2>&1 && item="Master"

    local result
    result="$(amixer sset Master "$action")"

    local volume="${result#*\[}"
    volume="${volume%%\%\]*}"

    local status="${result##*\[}"
    status="${status%\]}"

    local icon
    if [ x"$status" = x"off" ]; then
        icon=" Mute"
    else
        icon=""
    fi
    notify-send ":Adjust:" -i "${icon}" -h int:value:"${volume}"
}

"$@"
