#!/bin/sh

bspc config border_width        0
bspc config window_gap          10

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor --reset-desktops         
bscp desktop ^2 --layout monocle

bspc rule --add Chromium desktop=^3
bspc rule --add Gimp desktop=^6
bspc rule --add Gpick floating=on
bspc rule --add Iceweasel desktop=^2
bspc rule --add Screenkey manage=off
bspc rule --add mpv desktop=^7 floating=on

xsetroot -cursor_name left_ptr &
"$(dirname "$0")/panel" &
