#!/bin/sh

bspc config border_width        0
bspc config window_gap          10

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor --reset-desktops I II III IV V VI VII VIII IX X
bscp desktop ^2 --layout monocle

bspc rule --add Iceweasel desktop=^2
bspc rule --add Chromium desktop=^3
bspc rule --add Gimp desktop=^8
bspc rule --add mpv floating=on
bspc rule --add Screenkey manage=off

xsetroot -cursor_name left_ptr &
